grtr5 = int(input("Give a whole number that is greater than 5\n>"))
print(grtr5>5)
less99=int(input("Give a whole number that is less than 5\n>"))
print(less99<99)
grtr6=int(input("Give a whole number that is greater than 99\n>"))
print(grtr6>6)
grtr100=int(input("Give a whole number that is greater than 6\n>"))
print(grtr100>100)
less0=int(input("Give a whole number that is less than 0\n>"))
print(less0<0)