#The (adjective1) (noun1) felt (emotion1)
#as the (adjective2) (noun2) approached. 
#The onlooking (noun3) was too (adjective3) to stop the (noun2),
#causing the (noun4) to (verb) during the (acivity not ending in "ing")

ad1 = input("Input adjective\n>")
print("You chose " + ad1 + ".")
n1 = input("Input noun\n>")
print("You chose " + n1 + ".")
emote1 = input("Input emotion\n>")
print("You chose " + emote1 + ".")
ad2 = input("Input adjective\n>")
print("You chose " + ad2 + ".")
n2 = input("Input noun\n>")
print("You chose " + n2 + ".")
n3 = input("Input noun\n>")
print("You chose " + n3 + ".")
ad3 = input("Input adjective\n>")
print("You chose " + ad3 + ".")
n4 = input("Input noun\n>")
print("You chose " + n4 + ".")
v1 = input("Input verb NOT ENDING in 'ing'\n>")
print("You chose to " + v1 + ".")
act1 = input("Input an action or activity NOT ENDING in 'ing'.\n>")
print("You chose to " + act1 + ".")
print("Here is your generated MadLib:")
print(" ")
print(" ")
print("The "+ ad1 + " " + n1 + " felt "+emote1+" as the "+ ad2 + " "+ n2 +" approached. The onlooking "+n3+" was too "+ad3+" to stop the "+n2+", causing the "+n4+" to "+v1+" during the "+ act1 +".")
